### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by ghost** [raquo/minimal-hapi-react-webpack#8]
First super job here :-)

I tried to implement it with Docker, but I can't get it up and running

```

FROM node:4.2.2

RUN useradd --user-group --create-home --shell /bin/false app &&\
  npm install --global npm@3.7.5

ENV HOME=/home/app

COPY package.json npm-shrinkwrap.json $HOME/chat/
RUN chown -R app:app $HOME/*

USER app
WORKDIR $HOME/chat
RUN npm install

USER root
COPY . $HOME/chat
RUN chown -R app:app $HOME/*
USER app

CMD ["node", "run", "dev"]
```

```


chat:
  build: .
  command: node_modules/.bin/nodemon src/server.js dev
  environment:
    NODE_ENV: development
  ports:
    - '3000:3000'
  volumes:
    - .:/home/app/chat
    - /home/app/chat/node_modules

```

```
npm info it worked if it ends with ok
npm info using npm@3.7.5
npm info using node@v4.2.2
npm info lifecycle minimal-hapi-react-webpack-hmr-sandbox@3.1.0~prebuild: minimal-hapi-react-webpack-hmr-sandbox@3.1.0
npm info lifecycle minimal-hapi-react-webpack-hmr-sandbox@3.1.0~build: minimal-hapi-react-webpack-hmr-sandbox@3.1.0

> minimal-hapi-react-webpack-hmr-sandbox@3.1.0 build /home/app/chat
> NODE_ENV=production     node --harmony src/scripts/make.js  &&  NODE_ENV=production   webpack -p --config src/config/webpack-config.js

module.js:339
    throw err;
    ^

Error: Cannot find module '/home/app/chat/src/scripts/make.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:136:18)
    at node.js:963:3

```

The only error I got during the docker-compose build is 

```

> ws@0.4.31 install /home/app/chat/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/home/app/chat/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:92: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/home/app/chat/node_modules/ws/build'

```

Regarding https://github.com/websockets/bufferutil/issues/15 I tried to set dependencie in package as 

`
    "bufferutil": "^1.2.0",
`

But didn't solve anything... any idea is welcome :-)

**Comment by raquo** [comment]
Hm, let's see... Everything seems to fall apart the first time your script tries to access a project file from within Docker.

Are you sure that your docker-compose configuration actually copies over the project files into the right place inside the Docker container?

If you ssh into the docker container, and run `ls /home/app/chat/src/scripts/make.js`, does it show the file as expected? If not, my guess is that something is wrong here:

```
volumes:
    - .:/home/app/chat
    - /home/app/chat/node_modules
```

Or maybe in one of the `COPY` commands.

I only use Docker tangentially so I don't see any obvious errors.

**Comment by raquo** [comment]
Closing for inactivity
